# Generated by Django 4.1.1 on 2025-04-14 12:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Airport name', max_length=100)),
                ('code', models.CharField(help_text='IATA code, 3 letter unique code for airports', max_length=3)),
                ('standard_plane_ticket', models.IntegerField(default=100, help_text='Ticket price')),
                ('airport_pick_up_cost', models.PositiveIntegerField(default=10, help_text='Price picking up from airport')),
                ('airport_drop_off_cost', models.PositiveIntegerField(default=10, help_text='Price for dropping of to the airport')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('meal_plan', models.CharField(choices=[('None', 'No Meal Plan'), ('BB', 'Bed and Breakfast'), ('HB', 'Half Board'), ('FB', 'Full Board'), ('AI', 'All Inclusive')], default='None', help_text='Select meal plan for booking', max_length=4)),
                ('tickets_adult', models.PositiveIntegerField(default=1, help_text='Tickets for adults', validators=[django.core.validators.MinValueValidator(1)])),
                ('tickets_child', models.PositiveIntegerField(default=0, help_text=' Tickets for children')),
                ('wants_flight', models.BooleanField(default=False, help_text='Include flight tickets?')),
                ('wants_airport_pickup', models.BooleanField(default=False, help_text='Pick up from airport?')),
                ('wants_airport_dropoff', models.BooleanField(default=False, help_text='Drop off at airport?')),
                ('airport_price', models.IntegerField(default=0, help_text='Total cost of airport services')),
                ('wants_car_rental', models.BooleanField(default=False, help_text='Include car rental?')),
                ('car_rental_days', models.IntegerField(default=0, help_text='Car rental days')),
                ('car_rental_cost', models.IntegerField(default=0, help_text='Total cost of car rental services')),
                ('booking_price', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('from_airport', models.ForeignKey(blank=True, help_text='Departure Airport', null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.airport')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='City name', max_length=30)),
                ('description', models.TextField(blank=True, help_text='City description', null=True)),
                ('car_rental_option', models.BooleanField(help_text='Car rental option')),
                ('car_rental_cost', models.IntegerField(blank=True, help_text='Car rental cost per day in this City', null=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Continent name', max_length=30, unique=True)),
                ('description', models.TextField(blank=True, help_text='Continent description', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hotel name', max_length=100)),
                ('stars', models.PositiveIntegerField(help_text='Hotel Stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(help_text='Description of the hotel')),
                ('capacity', models.PositiveIntegerField(help_text='Hotel capacity reserved for our agency')),
                ('price_per_day', models.DecimalField(decimal_places=2, help_text='Base price per day', max_digits=10)),
                ('bb_price', models.DecimalField(blank=True, decimal_places=2, help_text='Additional price per day for Bed & Breakfast', max_digits=10, null=True)),
                ('hb_price', models.DecimalField(blank=True, decimal_places=2, help_text='Additional price per day for Half Board', max_digits=10, null=True)),
                ('fb_price', models.DecimalField(blank=True, decimal_places=2, help_text='Additional price per day for Full Board', max_digits=10, null=True)),
                ('ai_price', models.DecimalField(blank=True, decimal_places=2, help_text='Additional price per day for All Inclusive', max_digits=10, null=True)),
                ('city', models.ForeignKey(help_text='City', on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='travel.city')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(help_text='When trip begins')),
                ('return_date', models.DateField(help_text='When trip ends')),
                ('profit_on_adult', models.DecimalField(decimal_places=2, default=0.12, help_text='example: 0.10 represent 10 % of hotel price to be added to the final cost', max_digits=10)),
                ('profit_on_child', models.DecimalField(decimal_places=2, default=0.08, help_text='example: 0.10 represent 10 % of hotel price to be added to the final cost', max_digits=10)),
                ('tickets', models.PositiveIntegerField(default=1, help_text='Number of tickets including adults and children')),
                ('promoted', models.BooleanField(default=False, help_text='Check if this trip is going to promoted section of trips')),
                ('airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airport_trips', to='travel.airport')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_trips', to='travel.city')),
                ('hotel', models.ForeignKey(help_text='Hotel where clients make bookings', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_trips', to='travel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Country name', max_length=30, unique=True)),
                ('description', models.TextField(blank=True, help_text='Country description', null=True)),
                ('continent', models.ForeignKey(help_text='Continent', on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='travel.continent')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(help_text='Country', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='travel.country'),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.trip'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(help_text='City', on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='travel.city'),
        ),
    ]
