# Generated by Django 4.1.1 on 2025-04-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='available',
            field=models.BooleanField(default=True, help_text='If trip is available'),
        ),
    ]
