# Generated by Django 4.1.1 on 2025-04-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_remove_invoice_invoice_number_alter_invoice_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='city_images/'),
        ),
        migrations.AddField(
            model_name='continent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='continent_images/'),
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='country_images/'),
        ),
    ]
