# Generated by Django 4.1.1 on 2025-05-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_hotelimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='airplane_price',
            field=models.IntegerField(default=0, help_text='Plane Tickets cost'),
        ),
    ]
