# Generated by Django 4.1.1 on 2025-05-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reply_message',
            field=models.TextField(blank=True),
        ),
    ]
