# Generated by Django 4.1.1 on 2025-05-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_contactmessage_replied_contactmessage_replied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
