# Generated by Django 4.1.1 on 2025-05-14 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_booking_booking_number'),
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(blank=True, help_text='City of the user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='travel.city'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country of the user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='travel.country'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, help_text='First name of the user', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(blank=True, help_text='Last name of the user', max_length=50, null=True),
        ),
    ]
